import type { Program, GrantSource } from "./model";
// Starter watchlist, not a claim that these programs currently accept applications.
// Dates and awards must be recorded in separately reviewed application rounds.
export const starterPrograms: Array<{ id: string; data: Program }> = [
  [
    "sbif",
    "Small Business Improvement Fund",
    "City of Chicago / SomerCor",
    "public",
    "reimbursement",
    "hybrid",
    "https://somercor.com/sbif/",
    "Commercial improvements; rollout and applicant-specific rules require review.",
  ],
  [
    "nof",
    "Neighborhood Opportunity Fund",
    "City of Chicago",
    "public",
    "reimbursement",
    "hybrid",
    "https://www.chicago.gov/city/en/sites/neighborhood-opportunity-fund/home.html",
    "Commercial projects; confirm current-round eligibility and exclusions.",
  ],
  [
    "cdg-small",
    "Community Development Grant — Small",
    "City of Chicago",
    "public",
    "reimbursement",
    "hybrid",
    "https://www.chicago.gov/city/en/sites/community-development-grant/home/small_grants.html",
    "Review the current program manual, costs and project restrictions.",
  ],
  [
    "cdg-medium",
    "Community Development Grant — Medium",
    "City of Chicago",
    "public",
    "grant",
    "hybrid",
    "https://www.chicago.gov/city/en/sites/community-development-grant/home/medium_grants.html",
    "Medium-project funding; verify grant versus loan terms for the project.",
  ],
  [
    "workforce",
    "Workforce Solutions",
    "City of Chicago",
    "public",
    "reimbursement",
    "hybrid",
    "https://www.eesforjobs.com/workforce-solutions-program/",
    "Training support; confirm intake pathway, district and timing.",
  ],
  [
    "ssa50",
    "SSA #50 Facade Enhancement",
    "Southeast Chicago Chamber",
    "public",
    "reimbursement",
    "recurring",
    "https://southeastchgochamber.org/ssa-facade-enhancement-grants/",
    "Confirm available funds and frontage eligibility before work.",
  ],
  [
    "verizon",
    "Verizon Small Business Digital Ready",
    "Verizon / LISC",
    "corporate",
    "grant",
    "hybrid",
    "https://www.verizon.com/about/responsibility/digital-inclusion/small-business-training",
    "Training and grant rounds; current award and course requirements need verification.",
  ],
  [
    "nase",
    "NASE Growth Grants",
    "National Association for the Self-Employed",
    "community",
    "grant",
    "hybrid",
    "https://www.nase.org/become-a-member/member-benefits/business-resources/growth-grants",
    "Member funding; verify waiting periods and membership costs.",
  ],
  [
    "awesome",
    "Awesome Foundation — Chicago",
    "Awesome Foundation",
    "philanthropic",
    "grant",
    "hybrid",
    "https://www.awesomefoundation.org/en/chapters/chicago",
    "Community project funding; distinguish small project support from business capital.",
  ],
  [
    "awesome-disability",
    "Awesome Foundation — Disability",
    "Awesome Foundation",
    "philanthropic",
    "grant",
    "hybrid",
    "https://www.awesomefoundation.org/en/chapters/disability",
    "Review each application window and community-project criteria.",
  ],
  [
    "kiva",
    "Kiva US",
    "Kiva",
    "community",
    "loan",
    "recurring",
    "https://www.kiva.org/borrow",
    "Repayable financing; not a grant. Confirm operating history and eligibility.",
  ],
].map(
  ([
    id,
    name,
    sponsor,
    sponsorType,
    fundingType,
    cadence,
    sourceUrl,
    description,
  ]) => ({
    id: `starter-${id}`,
    data: {
      name,
      sponsor,
      sponsorType,
      fundingType,
      cadence,
      sourceUrl,
      description,
      archived: false,
      notes:
        "Imported as a research lead on September 11, 2026. No application round is verified by this starter record.",
      ownerId: null,
      tags: [],
    } as Program,
  }),
);
export const starterSources: Array<{ id: string; data: GrantSource }> = [
  ...starterPrograms.map((p) => ({
    id: `source-${p.id}`,
    data: {
      name: p.data.name,
      url: p.data.sourceUrl,
      kind: "program" as const,
      programId: p.id,
      intervalDays: 7,
      enabled: true,
      ownerId: null,
      notes:
        "Official/source watchlist; failed or blocked scans need manual review.",
      tags: [],
    },
  })),
  ...[
    [
      "city-intake",
      "City of Chicago funding applications",
      "https://cocdpd.submittable.com/submit",
    ],
    [
      "dceo",
      "Illinois DCEO grant opportunities",
      "https://dceo.illinois.gov/aboutdceo/grantopportunities.html",
    ],
    [
      "chicago-community-trust",
      "Chicago Community Trust funding opportunities",
      "https://www.cct.org/grants/",
    ],
    [
      "lisc",
      "LISC small business resources",
      "https://www.lisc.org/our-initiatives/small-business/",
    ],
  ].map(([id, name, url]) => ({
    id: `source-${id}`,
    data: {
      name,
      url,
      kind: "directory" as const,
      programId: null,
      intervalDays: 7,
      enabled: true,
      ownerId: null,
      notes: "Directory links are discovery leads, not verified opportunities.",
      tags: [],
    },
  })),
];
