import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(req: NextRequest) {
  try {
    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        { error: "Email service not configured" },
        { status: 503 }
      );
    }

    const { email, pdfBase64, filename, businessName, address, incentiveCount } =
      await req.json();

    if (!email || !pdfBase64) {
      return NextResponse.json(
        { error: "Email and PDF data are required" },
        { status: 400 }
      );
    }

    const resend = new Resend(process.env.RESEND_API_KEY);

    const subject = businessName
      ? `Incentive Report — ${businessName}`
      : `Chicago Incentive Report — ${address || "Your Location"}`;

    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL || "Chicago Incentive Explorer <onboarding@resend.dev>",
      to: [email],
      subject,
      html: `
        <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #0C1B33;">
          <div style="background: #0C1B33; padding: 32px 24px; text-align: center;">
            <h1 style="color: #fff; font-size: 22px; margin: 0 0 4px;">Chicago Business Incentive Report</h1>
            <p style="color: rgba(255,255,255,0.6); font-size: 13px; margin: 0;">Southeast Chicago Chamber of Commerce</p>
          </div>
          <div style="padding: 32px 24px;">
            <p style="font-size: 15px; line-height: 1.6; margin: 0 0 16px;">
              Your incentive report is attached as a PDF.
            </p>
            ${businessName ? `<p style="font-size: 14px; color: #6B7280; margin: 0 0 8px;"><strong>Business:</strong> ${businessName}</p>` : ""}
            ${address ? `<p style="font-size: 14px; color: #6B7280; margin: 0 0 8px;"><strong>Address:</strong> ${address}</p>` : ""}
            ${incentiveCount != null ? `<p style="font-size: 14px; color: #6B7280; margin: 0 0 24px;"><strong>Eligible Programs:</strong> ${incentiveCount}</p>` : ""}
            <div style="background: #F8FAFC; border-left: 3px solid #2563EB; padding: 16px; margin: 24px 0;">
              <p style="font-size: 13px; color: #6B7280; margin: 0; line-height: 1.5;">
                This report is informational and does not guarantee eligibility. Contact program administrators for official determinations.
              </p>
            </div>
            <p style="font-size: 13px; color: #6B7280; margin: 24px 0 0; line-height: 1.5;">
              Need help? Contact the Southeast Chicago Chamber of Commerce at (773) 721-1999 or visit
              <a href="https://www.secchicago.org" style="color: #2563EB;">secchicago.org</a>.
            </p>
          </div>
          <div style="background: #F8FAFC; padding: 16px 24px; text-align: center; border-top: 1px solid #E5E7EB;">
            <p style="font-size: 11px; color: #9CA3AF; margin: 0;">
              Generated by <a href="https://chicagoincentiveexplorer.com" style="color: #2563EB;">Chicago Incentive Explorer</a>
            </p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: filename || "chicago-incentive-report.pdf",
          content: Buffer.from(pdfBase64, "base64"),
        },
      ],
    });

    return NextResponse.json({ success: true });
  } catch (err) {
    console.error("Email route error:", err);
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}
