import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { z } from "zod";
import {
  createReportLead,
  markReportEmailDelivery,
  markReportLeadDelivered,
  reportEmailClientIdentifier,
  ReportEmailStorageUnavailableError,
  reserveReportEmailDelivery,
} from "@/lib/report-email-delivery";

export const runtime = "nodejs";

const MAX_REQUEST_BYTES = 6_500_000;
const MAX_PDF_BYTES = 4_500_000;

const EmailReportSchema = z.object({
  email: z.string().trim().toLowerCase().email().max(254),
  pdfBase64: z.string().min(100).max(6_000_000),
  filename: z.string().trim().max(180).optional(),
  businessName: z.string().trim().max(180).optional(),
  name: z.string().trim().max(120).optional(),
  address: z.string().trim().max(320).optional(),
  zipCode: z.string().trim().max(10).optional(),
  reportType: z.string().trim().max(80).optional(),
  projectGoal: z.string().trim().max(120).optional(),
  projectType: z.string().trim().max(80).optional(),
  source: z.string().trim().max(100).optional().default("report_email_modal"),
  incentiveCount: z.number().int().min(0).max(500).optional(),
  wantsHelp: z.boolean().optional().default(false),
  website: z.string().max(200).optional().default(""),
});

function escapeHtml(value: string): string {
  return value.replace(/[&<>'"]/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    "'": "&#39;",
    '"': "&quot;",
  })[character] || character);
}

function safePdfFilename(value?: string): string {
  const basename = (value || "chicago-incentive-report.pdf")
    .split(/[\\/]/)
    .pop()
    ?.replace(/[^a-zA-Z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 150) || "chicago-incentive-report.pdf";
  return basename.toLowerCase().endsWith(".pdf") ? basename : `${basename}.pdf`;
}

function decodePdf(value: string): Buffer | null {
  if (!/^[A-Za-z0-9+/]+={0,2}$/.test(value)) return null;
  const pdf = Buffer.from(value, "base64");
  if (pdf.length === 0 || pdf.length > MAX_PDF_BYTES) return null;
  if (pdf.subarray(0, 5).toString("ascii") !== "%PDF-") return null;
  return pdf;
}

function recipientEmailHtml(input: z.infer<typeof EmailReportSchema>): string {
  const name = input.name ? escapeHtml(input.name) : "";
  const address = input.address ? escapeHtml(input.address) : "";
  const goal = input.projectGoal ? escapeHtml(input.projectGoal) : "";
  const greeting = name ? `Hi ${name},` : "Your incentive report is ready.";
  const helpCopy = input.wantsHelp
    ? "You asked for Chamber support. Your request is in the follow-up queue, and a team member can use the email address you provided to reach you."
    : "You did not request Chamber follow-up. We will use this email address to deliver your report.";

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #0C1B33;">
      <div style="background: #0C1B33; padding: 28px 24px;">
        <h1 style="color: #fff; font-size: 22px; margin: 0 0 6px;">Chicago Business Incentive Report</h1>
        <p style="color: rgba(255,255,255,0.68); font-size: 13px; margin: 0;">Southeast Chicago Chamber of Commerce</p>
      </div>
      <div style="padding: 30px 24px;">
        <p style="font-size: 15px; line-height: 1.6; margin: 0 0 16px;">${greeting}</p>
        <p style="font-size: 14px; line-height: 1.6; margin: 0 0 20px;">Your PDF report is attached.</p>
        ${address ? `<p style="font-size: 14px; color: #4B5563; margin: 0 0 8px;"><strong>Address:</strong> ${address}</p>` : ""}
        ${goal ? `<p style="font-size: 14px; color: #4B5563; margin: 0 0 8px;"><strong>Primary goal:</strong> ${goal}</p>` : ""}
        ${input.incentiveCount != null ? `<p style="font-size: 14px; color: #4B5563; margin: 0 0 20px;"><strong>Programs surfaced:</strong> ${input.incentiveCount}</p>` : ""}
        <div style="background: #F8FAFC; border-left: 3px solid #2563EB; padding: 16px; margin: 22px 0;">
          <p style="font-size: 13px; color: #4B5563; margin: 0; line-height: 1.5;">${helpCopy}</p>
        </div>
        <p style="font-size: 12px; color: #6B7280; margin: 0; line-height: 1.5;">This report is informational and does not guarantee eligibility. Confirm requirements with each program administrator before acting.</p>
      </div>
      <div style="background: #F8FAFC; padding: 16px 24px; border-top: 1px solid #E5E7EB;">
        <p style="font-size: 11px; color: #9CA3AF; margin: 0;">Generated by Chicago Incentive Explorer</p>
      </div>
    </div>
  `;
}

function helpNotificationHtml(input: z.infer<typeof EmailReportSchema>): string {
  const name = escapeHtml(input.name || "Report recipient");
  const email = escapeHtml(input.email);
  const address = escapeHtml(input.address || "Not provided");
  const goal = escapeHtml(input.projectGoal || input.projectType || "Not provided");
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; color: #0C1B33;">
      <h1 style="font-size: 20px;">Incentive help requested</h1>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Address:</strong> ${address}</p>
      <p><strong>Primary goal:</strong> ${goal}</p>
      <p>The report was delivered successfully and this request was added to the analytics follow-up queue.</p>
    </div>
  `;
}

export async function POST(req: NextRequest) {
  if (process.env.REPORT_EMAILS_ENABLED !== "true") {
    return NextResponse.json(
      { error: "Report email delivery is temporarily unavailable." },
      { status: 503 },
    );
  }

  const contentLength = Number(req.headers.get("content-length") || 0);
  if (contentLength > MAX_REQUEST_BYTES) {
    return NextResponse.json({ error: "Report attachment is too large." }, { status: 413 });
  }

  const rawBody = await req.json().catch(() => null);
  const parsed = EmailReportSchema.safeParse(rawBody);
  if (!parsed.success) {
    return NextResponse.json({ error: "Enter a valid email and report." }, { status: 400 });
  }
  const input = parsed.data;

  // Honeypot submissions receive a neutral success response without delivery.
  if (input.website) {
    return NextResponse.json({ success: true });
  }

  const pdf = decodePdf(input.pdfBase64);
  if (!pdf) {
    return NextResponse.json({ error: "The report PDF is invalid." }, { status: 400 });
  }

  const dryRun = process.env.NODE_ENV !== "production"
    && process.env.REPORT_EMAIL_DRY_RUN === "true";
  if (dryRun) {
    return NextResponse.json({ success: true, dryRun: true });
  }

  if (!process.env.RESEND_API_KEY) {
    return NextResponse.json(
      { error: "Report email delivery is temporarily unavailable." },
      { status: 503 },
    );
  }

  let reservationId: number | null = null;
  let leadId: number | null = null;
  try {
    const reservation = await reserveReportEmailDelivery(
      input.email,
      reportEmailClientIdentifier(req.headers),
    );
    if (!reservation.allowed) {
      return NextResponse.json(
        { error: "Too many report emails were requested. Please try again later." },
        {
          status: 429,
          headers: { "Retry-After": String(reservation.retryAfterSeconds) },
        },
      );
    }
    reservationId = reservation.id;

    leadId = await createReportLead({
      name: input.name,
      email: input.email,
      zipCode: input.zipCode,
      reportAddress: input.address,
      reportTitle: input.businessName,
      reportType: input.reportType,
      projectGoal: input.projectGoal,
      wantsHelp: input.wantsHelp,
      source: input.source,
    });

    const resend = new Resend(process.env.RESEND_API_KEY);
    const subjectTarget = (input.address || input.businessName || "Your Location")
      .replace(/[\r\n]+/g, " ")
      .slice(0, 180);
    const delivery = await resend.emails.send({
      from: process.env.REPORT_EMAIL_FROM
        || "Chicago Incentive Explorer <reports@chicagoincentiveexplorer.com>",
      to: [input.email],
      subject: `Chicago Incentive Report - ${subjectTarget}`,
      html: recipientEmailHtml(input),
      text: [
        input.name ? `Hi ${input.name},` : "Your incentive report is ready.",
        "Your PDF report is attached.",
        input.address ? `Address: ${input.address}` : "",
        input.projectGoal ? `Primary goal: ${input.projectGoal}` : "",
        input.wantsHelp
          ? "You requested follow-up from the Southeast Chicago Chamber of Commerce."
          : "No Chamber follow-up was requested.",
        "This report is informational and does not guarantee eligibility.",
      ].filter(Boolean).join("\n\n"),
      attachments: [
        {
          filename: safePdfFilename(input.filename),
          content: pdf,
        },
      ],
    });
    if (delivery.error) throw new Error("Resend rejected the report email");

    if (input.wantsHelp && process.env.INCENTIVE_HELP_INBOX) {
      try {
        const notification = await resend.emails.send({
          from: process.env.REPORT_EMAIL_FROM
            || "Chicago Incentive Explorer <reports@chicagoincentiveexplorer.com>",
          to: [process.env.INCENTIVE_HELP_INBOX],
          replyTo: input.email,
          subject: `Incentive help requested - ${input.address || input.email}`,
          html: helpNotificationHtml(input),
          text: `Incentive help requested\n\nName: ${input.name || "Report recipient"}\nEmail: ${input.email}\nAddress: ${input.address || "Not provided"}\nPrimary goal: ${input.projectGoal || input.projectType || "Not provided"}`,
        });
        if (notification.error) {
          console.error("Incentive help notification was not accepted by Resend");
        }
      } catch (notificationError) {
        console.error("Incentive help notification failed:", notificationError);
      }
    }

    const storageUpdates = await Promise.allSettled([
      markReportEmailDelivery(reservationId, "sent"),
      markReportLeadDelivered(leadId),
    ]);
    if (storageUpdates.some((result) => result.status === "rejected")) {
      console.error("Report email was delivered but delivery metadata was not fully updated");
    }

    return NextResponse.json({ success: true, helpRequested: input.wantsHelp });
  } catch (error) {
    if (reservationId != null) {
      await markReportEmailDelivery(reservationId, "failed").catch(() => undefined);
    }
    if (error instanceof ReportEmailStorageUnavailableError) {
      return NextResponse.json(
        { error: "Report email delivery is temporarily unavailable." },
        { status: 503 },
      );
    }
    console.error("Email report delivery failed:", error);
    return NextResponse.json(
      { error: "We could not email the report. Please try again." },
      { status: 502 },
    );
  }
}
