"use client";

import { StackingScore } from "./StackingScore";
import { ZoneResultCard } from "./ZoneResultCard";
import { ZONE_KEYS, ZONE_COLORS, ZONE_LABELS } from "@/lib/constants";
import type { LookupResult, Program } from "@/lib/types";
import { Building2, MapPin, Copy, Mail, Check, Layers, TrendingDown, Users, FileText, Landmark, ExternalLink, Phone } from "lucide-react";
import { useState, useCallback } from "react";
import { EmailReportDialog } from "./EmailReportDialog";

function getUnemploymentColor(rateStr: string): string {
  const rate = parseFloat(rateStr);
  if (isNaN(rate)) return "#ea580c";
  if (rate >= 30) return "#dc2626";
  if (rate >= 20) return "#ea580c";
  if (rate >= 10) return "#d97706";
  return "#16a34a";
}

interface IncentiveReportProps {
  result: LookupResult;
  programs: Program[];
}

export function IncentiveReport({ result, programs }: IncentiveReportProps) {
  const [copied, setCopied] = useState(false);
  const [emailOpen, setEmailOpen] = useState(false);
  const programMap = new Map(programs.map((p) => [p.zoneKey, p]));

  const buildReportText = useCallback(() => {
    const name = result.business?.name || "Address Lookup";
    const address = result.business
      ? `${result.business.address}, Chicago, IL ${result.business.zip}`
      : result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`;

    const eligible = ZONE_KEYS
      .filter((k) => result.zones[k])
      .map((k) => programMap.get(k)?.name || k)
      .join("\n  - ");

    const zoneNameEntries = Object.entries(result.zoneNames || {});
    const zoningSection = zoneNameEntries.length > 0
      ? `\nZoning Districts:\n${zoneNameEntries.map(([k, v]) => `  - ${ZONE_LABELS[k] || k}: ${v}`).join("\n")}\n`
      : "";

    const cityZoningSection = result.cityZoning
      ? `\nCity Zoning: ${result.cityZoning.zoneClass}${result.cityZoning.zoneType ? ` (${result.cityZoning.zoneType})` : ""}\n`
      : "";

    const employmentSection = result.employment?.unemploymentRate
      ? `\nEmployment:\n  Census Tract: ${result.employment.censusTract}\n  Unemployment Rate: ${result.employment.unemploymentRate}\n  Status: High Unemployment Zone\n`
      : "";

    return `Chicago Site Incentive Report
========================
Business: ${name}
Address: ${address}
Incentive Score: ${result.incentiveCount} of ${ZONE_KEYS.length} zones
${cityZoningSection}${zoningSection}${employmentSection}
Eligible Programs:
  - ${eligible || "None found"}

Property Valuation:
  Cook County Assessor's Office
  How Commercial Properties Are Valued:
  https://www.cookcountyassessoril.gov/commercial/how-commercial-properties-are-valued

Generated by Chicago Site Incentive Map`;
  }, [result, programMap]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = () => setEmailOpen(true);

  const handleDownloadPDF = async () => {
    const { generateReport } = await import("@/lib/pdf-report");
    generateReport(result, programs);
  };

  const sortedKeys = [...ZONE_KEYS].sort((a, b) => {
    const aIn = result.zones[a] ? 1 : 0;
    const bIn = result.zones[b] ? 1 : 0;
    if (aIn !== bIn) return bIn - aIn;
    return a.localeCompare(b);
  });

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-3 pb-8 border-b border-white/10">
        {result.matched && result.business ? (
          <>
            <div className="flex items-center justify-center gap-2">
              <Building2 className="w-4 h-4 text-green-400" />
              <span className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-green-400">
                Matched Business
              </span>
            </div>
            <h2 className="font-editorial text-2xl text-white">{result.business.name}</h2>
            <p className="text-sm text-white/40 flex items-center justify-center gap-1">
              <MapPin className="w-3 h-3" />
              {result.business.address}, Chicago, IL {result.business.zip}
            </p>
            {result.business.category && (
              <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/25">
                {result.business.category}
              </span>
            )}
          </>
        ) : (
          <p className="text-sm text-white/40 flex items-center justify-center gap-1">
            <MapPin className="w-3 h-3" />
            {result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`}
          </p>
        )}

        {/* City Zoning Classification */}
        {result.cityZoning && (
          <div className="flex items-center justify-center gap-2 mt-2">
            <Landmark className="w-3.5 h-3.5 text-[#2563EB]/70" />
            <span className="font-mono-bureau text-[10px] tracking-[0.15em] text-[#2563EB]">
              {result.cityZoning.zoneClass}
            </span>
            {result.cityZoning.zoneType && (
              <span className="font-mono-bureau text-[9px] tracking-[0.1em] text-white/30">
                {result.cityZoning.zoneType}
              </span>
            )}
          </div>
        )}
      </div>

      {/* Stacking Score */}
      <StackingScore score={result.incentiveCount} />

      {/* Location Context */}
      {(Object.keys(result.zoneNames || {}).length > 0 || result.employment || result.cityZoning) && (
        <div className="space-y-3">
          <div className="flex items-center gap-4 mb-1">
            <div className="accent-bar-light" />
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
              Location Context
            </h3>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            {/* City Zoning Ordinance */}
            {result.cityZoning && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Landmark className="w-4 h-4 text-[#2563EB]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    City Zoning Ordinance
                  </span>
                </div>
                <div className="flex items-baseline gap-2 mb-1">
                  <span className="font-editorial text-2xl text-[#2563EB]">
                    {result.cityZoning.zoneClass}
                  </span>
                </div>
                {result.cityZoning.zoneType && (
                  <div className="font-mono-bureau text-[9px] tracking-[0.1em] text-white/40">
                    {result.cityZoning.zoneType}
                  </div>
                )}
                <div className="mt-3 pt-3 border-t border-white/5">
                  <p className="text-[10px] text-white/30 leading-relaxed">
                    Per Chicago Municipal Code. Zoning determines permitted land uses, building types, and density at this location.
                  </p>
                </div>
              </div>
            )}

            {/* Incentive Zoning Districts */}
            {Object.keys(result.zoneNames || {}).length > 0 && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Layers className="w-4 h-4 text-[#2563EB]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    Incentive Districts
                  </span>
                </div>
                <div className="space-y-2">
                  {Object.entries(result.zoneNames || {}).map(([key, name]) => (
                    <div key={key} className="flex items-start gap-2">
                      <div
                        className="w-2 h-2 rounded-full mt-1.5 shrink-0"
                        style={{ backgroundColor: ZONE_COLORS[key] || "#6b7280" }}
                      />
                      <div>
                        <div className="text-xs text-white/60">{name}</div>
                        <div className="font-mono-bureau text-[8px] tracking-[0.15em] uppercase text-white/25">
                          {ZONE_LABELS[key] || key}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Employment Indicator */}
            {result.employment && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Users className="w-4 h-4 text-[#ea580c]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    Employment Level
                  </span>
                </div>
                {result.employment.unemploymentRate && (
                  <div className="mb-3">
                    <div className="flex items-baseline gap-2 mb-1">
                      <span className="font-editorial text-2xl text-[#ea580c]">
                        {result.employment.unemploymentRate}
                      </span>
                      <span className="font-mono-bureau text-[9px] tracking-[0.1em] uppercase text-white/30">
                        unemployment
                      </span>
                    </div>
                    <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{
                          width: result.employment.unemploymentRate,
                          backgroundColor: getUnemploymentColor(result.employment.unemploymentRate),
                        }}
                      />
                    </div>
                    <div className="flex justify-between mt-1">
                      <span className="font-mono-bureau text-[7px] text-white/20">0%</span>
                      <span className="font-mono-bureau text-[7px] text-white/20">50%</span>
                    </div>
                  </div>
                )}
                <div className="space-y-1.5">
                  <div className="flex items-center gap-2">
                    <TrendingDown className="w-3 h-3 text-[#ea580c]/60" />
                    <span className="text-xs text-white/50">High Unemployment Zone</span>
                  </div>
                  {result.employment.censusTract && (
                    <div className="font-mono-bureau text-[8px] tracking-[0.15em] uppercase text-white/25">
                      {result.employment.censusTract}
                    </div>
                  )}
                  {result.employment.population > 0 && (
                    <div className="font-mono-bureau text-[8px] tracking-[0.1em] text-white/25">
                      Pop. {result.employment.population.toLocaleString()}
                    </div>
                  )}
                </div>
                <div className="mt-3 pt-3 border-t border-white/5">
                  <p className="text-[10px] text-white/30 leading-relaxed">
                    Businesses hiring in this area may qualify for the Work Opportunity Tax Credit (WOTC) and workforce development incentives.
                  </p>
                </div>
              </div>
            )}

            {/* Cook County Assessor — Property Valuation */}
            <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
              <div className="flex items-center gap-2 mb-3">
                <Building2 className="w-4 h-4 text-[#7c3aed]" />
                <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                  Property Valuation
                </span>
              </div>
              <h4 className="text-sm font-medium text-white/80 mb-1">
                Cook County Assessor
              </h4>
              <p className="text-[10px] text-white/30 leading-relaxed mb-3">
                The Cook County Assessor&rsquo;s Office determines the assessed value of commercial
                properties for tax purposes. Understanding your property&rsquo;s valuation can help
                you estimate tax incentive savings and appeal assessments.
              </p>
              <div className="space-y-2">
                <a
                  href="https://www.cookcountyassessoril.gov/address-search"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-[11px] text-[#7c3aed] hover:text-[#9b6dff] transition-colors font-mono-bureau tracking-wide"
                >
                  <ExternalLink className="w-3 h-3" />
                  Assessor Address Search
                </a>
                <a
                  href="https://www.cookcountyclerkil.gov/recordings/search-recordings"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-[11px] text-[#7c3aed] hover:text-[#9b6dff] transition-colors font-mono-bureau tracking-wide"
                >
                  <ExternalLink className="w-3 h-3" />
                  Search Property Recordings
                </a>
                <a
                  href="https://www.cookcountyassessoril.gov/commercial/how-commercial-properties-are-valued"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-[11px] text-[#7c3aed]/60 hover:text-[#7c3aed] transition-colors font-mono-bureau tracking-wide"
                >
                  <ExternalLink className="w-3 h-3" />
                  How Commercial Properties Are Valued
                </a>
                <a
                  href="https://www.cookcountyassessoril.gov"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 text-[11px] text-[#7c3aed]/60 hover:text-[#7c3aed] transition-colors font-mono-bureau tracking-wide"
                >
                  <ExternalLink className="w-3 h-3" />
                  Cook County Assessor&rsquo;s Office
                </a>
              </div>
              <div className="mt-3 pt-3 border-t border-white/5">
                <p className="text-[10px] text-white/30 leading-relaxed">
                  Look up your property&rsquo;s PIN, assessed value, and deed recordings
                  to understand your property&rsquo;s full tax profile and ownership history.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Quick Actions */}
      {result.incentiveCount > 0 && (() => {
        const topZones = ZONE_KEYS.filter((k) => result.zones[k]).slice(0, 2);
        const topContacts = topZones
          .map((k) => programMap.get(k))
          .filter((p): p is Program => !!p && !!p.contacts?.[0]?.phone);

        if (topContacts.length === 0) return null;

        return (
          <div className="space-y-3">
            <div className="flex items-center gap-4 mb-1">
              <div className="accent-bar-light" />
              <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
                Start Here
              </h3>
            </div>
            {topContacts.map((p) => {
              const contact = p.contacts![0];
              return (
                <div key={p.id} className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                  <span className="text-sm text-white/70 font-medium block mb-1">{p.name}</span>
                  <span className="text-[10px] text-white/30 block mb-2">{contact.role || "Program Contact"}: {contact.agency}</span>
                  <div className="flex gap-2">
                    {contact.phone && (
                      <a
                        href={`tel:${contact.phone}`}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-[#2563EB]/20 border border-[#2563EB]/30 rounded-lg text-[10px] text-[#2563EB] font-mono-bureau hover:bg-[#2563EB]/30 transition-colors"
                      >
                        <Phone className="w-3 h-3" />
                        {contact.phone}
                      </a>
                    )}
                    {contact.email && (
                      <a
                        href={`mailto:${contact.email}`}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white/5 border border-white/10 rounded-lg text-[10px] text-white/50 font-mono-bureau hover:bg-white/10 transition-colors"
                      >
                        <Mail className="w-3 h-3" />
                        Email
                      </a>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        );
      })()}

      {/* Zone Cards */}
      <div>
        <div className="flex items-center gap-4 mb-4">
          <div className="accent-bar-light" />
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
            Programs ({result.incentiveCount} of {ZONE_KEYS.length} eligible)
          </h3>
        </div>
        <div className="space-y-1">
          {sortedKeys.map((key) => (
            <ZoneResultCard
              key={key}
              zoneKey={key}
              inZone={!!result.zones[key]}
              program={programMap.get(key)}
            />
          ))}
        </div>
      </div>

      {/* Export Actions */}
      {result.incentiveCount > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="accent-bar-light" />
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
              Export Report
            </h3>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleEmail}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <Mail className="w-4 h-4" />
              Email
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-[#2563EB] hover:bg-[#1d4ed8] text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <FileText className="w-4 h-4" />
              PDF Report
            </button>
          </div>
        </div>
      )}

      {/* Next Steps */}
      {result.incentiveCount > 0 && (() => {
        const eligiblePrograms = ZONE_KEYS
          .filter((k) => result.zones[k])
          .map((k) => programMap.get(k))
          .filter((p): p is Program => !!p);

        const topProgram = eligiblePrograms.find((p) => p.contacts?.[0]?.phone);
        const contact = topProgram?.contacts?.[0];

        return (
          <div className="border border-white/10 p-6 rounded-xl bg-white/[0.03]">
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/60 mb-4">
              Your Action Plan
            </h3>
            <div className="space-y-3">
              {topProgram && contact && (
                <div className="flex items-start gap-3">
                  <span className="w-5 h-5 bg-emerald-500/20 text-emerald-400 flex items-center justify-center text-[10px] font-semibold flex-shrink-0">1</span>
                  <div>
                    <span className="text-sm text-white/60 block">
                      Call {contact.agency} about {topProgram.name}
                    </span>
                    {contact.phone && (
                      <a href={`tel:${contact.phone}`} className="text-[11px] text-[#2563EB] font-mono-bureau">{contact.phone}</a>
                    )}
                  </div>
                </div>
              )}
              <div className="flex items-start gap-3">
                <span className="w-5 h-5 bg-amber-500/20 text-amber-400 flex items-center justify-center text-[10px] font-semibold flex-shrink-0">{topProgram ? "2" : "1"}</span>
                <span className="text-sm text-white/40">
                  Gather documents: proof of ownership, project plans, and cost estimates
                </span>
              </div>
              <div className="flex items-start gap-3">
                <span className="w-5 h-5 bg-white/10 text-white/40 flex items-center justify-center text-[10px] font-semibold flex-shrink-0">{topProgram ? "3" : "2"}</span>
                <span className="text-sm text-white/40">
                  Generate a full report for detailed analysis and PDF export
                </span>
              </div>
            </div>
          </div>
        );
      })()}

      {/* Email Dialog */}
      <EmailReportDialog
        result={result}
        programs={programs}
        open={emailOpen}
        onClose={() => setEmailOpen(false)}
      />
    </div>
  );
}
