"use client";

import { StackingScore } from "./StackingScore";
import { ZoneResultCard } from "./ZoneResultCard";
import { ZONE_KEYS, ZONE_COLORS, ZONE_LABELS } from "@/lib/constants";
import { INDUSTRIES } from "@/lib/industries-data";
import type { LookupResult, Program } from "@/lib/types";
import { Building2, MapPin, Copy, Mail, Download, Check, Layers, TrendingDown, Users, FileText, ChevronDown, Landmark } from "lucide-react";
import { useState, useCallback } from "react";

function getUnemploymentColor(rateStr: string): string {
  const rate = parseFloat(rateStr);
  if (isNaN(rate)) return "#ea580c";
  if (rate >= 30) return "#dc2626"; // red — very high
  if (rate >= 20) return "#ea580c"; // orange — high
  if (rate >= 10) return "#d97706"; // amber — elevated
  return "#16a34a"; // green — moderate
}

interface IncentiveReportProps {
  result: LookupResult;
  programs: Program[];
  onSectorChange?: (sector: string) => void;
}

export function IncentiveReport({ result, programs, onSectorChange }: IncentiveReportProps) {
  const [copied, setCopied] = useState(false);
  const [sectorOpen, setSectorOpen] = useState(false);
  const programMap = new Map(programs.map((p) => [p.zoneKey, p]));

  const buildReportText = useCallback(() => {
    const name = result.business?.name || "Address Lookup";
    const address = result.business
      ? `${result.business.address}, Chicago, IL ${result.business.zip}`
      : result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`;

    const eligible = ZONE_KEYS
      .filter((k) => result.zones[k])
      .map((k) => programMap.get(k)?.name || k)
      .join("\n  - ");

    const zoneNameEntries = Object.entries(result.zoneNames || {});
    const zoningSection = zoneNameEntries.length > 0
      ? `\nZoning Districts:\n${zoneNameEntries.map(([k, v]) => `  - ${ZONE_LABELS[k] || k}: ${v}`).join("\n")}\n`
      : "";

    const cityZoningSection = result.cityZoning
      ? `\nCity Zoning: ${result.cityZoning.zoneClass}${result.cityZoning.zoneType ? ` (${result.cityZoning.zoneType})` : ""}\n`
      : "";

    const employmentSection = result.employment?.unemploymentRate
      ? `\nEmployment:\n  Census Tract: ${result.employment.censusTract}\n  Unemployment Rate: ${result.employment.unemploymentRate}\n  Status: High Unemployment Zone\n`
      : "";

    return `Chicago Incentive Report
========================
Business: ${name}
Address: ${address}
Incentive Score: ${result.incentiveCount} of ${ZONE_KEYS.length} zones
${cityZoningSection}${zoningSection}${employmentSection}
Eligible Programs:
  - ${eligible || "None found"}

Generated by Chicago Incentive Explorer`;
  }, [result, programMap]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(
      `Incentive Report — ${result.business?.name || "Chicago Business"}`
    );
    const body = encodeURIComponent(buildReportText());
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleDownloadPDF = async () => {
    const { generateReport } = await import("@/lib/pdf-report");
    generateReport(result, programs);
  };

  const currentSector = result.sector
    ? INDUSTRIES.find((ind) => ind.id === result.sector)
    : null;

  const sortedKeys = [...ZONE_KEYS].sort((a, b) => {
    const aIn = result.zones[a] ? 1 : 0;
    const bIn = result.zones[b] ? 1 : 0;
    if (aIn !== bIn) return bIn - aIn;
    return a.localeCompare(b);
  });

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-3 pb-8 border-b border-white/10">
        {result.matched && result.business ? (
          <>
            <div className="flex items-center justify-center gap-2">
              <Building2 className="w-4 h-4 text-green-400" />
              <span className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-green-400">
                Matched Business
              </span>
            </div>
            <h2 className="font-editorial text-2xl text-white">{result.business.name}</h2>
            <p className="text-sm text-white/40 flex items-center justify-center gap-1">
              <MapPin className="w-3 h-3" />
              {result.business.address}, Chicago, IL {result.business.zip}
            </p>
            {result.business.category && (
              <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/25">
                {result.business.category}
              </span>
            )}
          </>
        ) : (
          <p className="text-sm text-white/40 flex items-center justify-center gap-1">
            <MapPin className="w-3 h-3" />
            {result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`}
          </p>
        )}

        {/* City Zoning Classification */}
        {result.cityZoning && (
          <div className="flex items-center justify-center gap-2 mt-2">
            <Landmark className="w-3.5 h-3.5 text-[#2563EB]/70" />
            <span className="font-mono-bureau text-[10px] tracking-[0.15em] text-[#2563EB]">
              {result.cityZoning.zoneClass}
            </span>
            {result.cityZoning.zoneType && (
              <span className="font-mono-bureau text-[9px] tracking-[0.1em] text-white/30">
                {result.cityZoning.zoneType}
              </span>
            )}
          </div>
        )}
      </div>

      {/* Sector Self-Identification */}
      <div className="space-y-2">
        <div className="flex items-center gap-4 mb-1">
          <div className="accent-bar-light" />
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
            Your Business Sector
          </h3>
        </div>
        <div className="relative">
          <button
            onClick={() => setSectorOpen(!sectorOpen)}
            className="w-full flex items-center justify-between gap-3 px-4 py-3 border border-white/10 rounded-xl bg-white/[0.03] hover:bg-white/[0.06] transition-all text-left"
          >
            {currentSector ? (
              <span className="flex items-center gap-2">
                <span className="text-lg">{currentSector.icon}</span>
                <span className="text-sm text-white/70">{currentSector.name}</span>
              </span>
            ) : (
              <span className="text-sm text-white/30">Select your sector to personalize your report...</span>
            )}
            <ChevronDown className={`w-4 h-4 text-white/30 transition-transform ${sectorOpen ? "rotate-180" : ""}`} />
          </button>

          {sectorOpen && (
            <div className="absolute z-20 w-full mt-1 bg-[#1E3054] border border-white/10 rounded-xl shadow-2xl max-h-72 overflow-y-auto">
              {INDUSTRIES.map((ind) => (
                <button
                  key={ind.id}
                  className={`w-full flex items-center gap-3 px-4 py-2.5 text-left hover:bg-white/[0.06] transition-colors border-b border-white/5 last:border-b-0 ${
                    result.sector === ind.id ? "bg-white/[0.08]" : ""
                  }`}
                  onClick={() => {
                    onSectorChange?.(ind.id);
                    setSectorOpen(false);
                  }}
                >
                  <span className="text-lg">{ind.icon}</span>
                  <div>
                    <div className="text-sm text-white/70">{ind.name}</div>
                    <div className="font-mono-bureau text-[8px] tracking-[0.1em] text-white/25">
                      {ind.topPrograms.length} programs
                    </div>
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Stacking Score */}
      <StackingScore score={result.incentiveCount} />

      {/* Location Context — City Zoning, Incentive Zones & Employment */}
      {(Object.keys(result.zoneNames || {}).length > 0 || result.employment || result.cityZoning) && (
        <div className="space-y-3">
          <div className="flex items-center gap-4 mb-1">
            <div className="accent-bar-light" />
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
              Location Context
            </h3>
          </div>

          <div className="grid gap-3 sm:grid-cols-2">
            {/* City Zoning Ordinance */}
            {result.cityZoning && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Landmark className="w-4 h-4 text-[#2563EB]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    City Zoning Ordinance
                  </span>
                </div>
                <div className="flex items-baseline gap-2 mb-1">
                  <span className="font-editorial text-2xl text-[#2563EB]">
                    {result.cityZoning.zoneClass}
                  </span>
                </div>
                {result.cityZoning.zoneType && (
                  <div className="font-mono-bureau text-[9px] tracking-[0.1em] text-white/40">
                    {result.cityZoning.zoneType}
                  </div>
                )}
                <div className="mt-3 pt-3 border-t border-white/5">
                  <p className="text-[10px] text-white/30 leading-relaxed">
                    Per Chicago Municipal Code. Zoning determines permitted land uses, building types, and density at this location.
                  </p>
                </div>
              </div>
            )}

            {/* Incentive Zoning Districts */}
            {Object.keys(result.zoneNames || {}).length > 0 && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Layers className="w-4 h-4 text-[#2563EB]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    Incentive Districts
                  </span>
                </div>
                <div className="space-y-2">
                  {Object.entries(result.zoneNames || {}).map(([key, name]) => (
                    <div key={key} className="flex items-start gap-2">
                      <div
                        className="w-2 h-2 rounded-full mt-1.5 shrink-0"
                        style={{ backgroundColor: ZONE_COLORS[key] || "#6b7280" }}
                      />
                      <div>
                        <div className="text-xs text-white/60">{name}</div>
                        <div className="font-mono-bureau text-[8px] tracking-[0.15em] uppercase text-white/25">
                          {ZONE_LABELS[key] || key}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Employment Indicator */}
            {result.employment && (
              <div className="border border-white/10 rounded-xl p-4 bg-white/[0.03]">
                <div className="flex items-center gap-2 mb-3">
                  <Users className="w-4 h-4 text-[#ea580c]" />
                  <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/50">
                    Employment Level
                  </span>
                </div>

                {/* Unemployment Rate Gauge */}
                {result.employment.unemploymentRate && (
                  <div className="mb-3">
                    <div className="flex items-baseline gap-2 mb-1">
                      <span className="font-editorial text-2xl text-[#ea580c]">
                        {result.employment.unemploymentRate}
                      </span>
                      <span className="font-mono-bureau text-[9px] tracking-[0.1em] uppercase text-white/30">
                        unemployment
                      </span>
                    </div>
                    <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{
                          width: result.employment.unemploymentRate,
                          backgroundColor: getUnemploymentColor(result.employment.unemploymentRate),
                        }}
                      />
                    </div>
                    <div className="flex justify-between mt-1">
                      <span className="font-mono-bureau text-[7px] text-white/20">0%</span>
                      <span className="font-mono-bureau text-[7px] text-white/20">50%</span>
                    </div>
                  </div>
                )}

                <div className="space-y-1.5">
                  <div className="flex items-center gap-2">
                    <TrendingDown className="w-3 h-3 text-[#ea580c]/60" />
                    <span className="text-xs text-white/50">
                      High Unemployment Zone
                    </span>
                  </div>
                  {result.employment.censusTract && (
                    <div className="font-mono-bureau text-[8px] tracking-[0.15em] uppercase text-white/25">
                      {result.employment.censusTract}
                    </div>
                  )}
                  {result.employment.population > 0 && (
                    <div className="font-mono-bureau text-[8px] tracking-[0.1em] text-white/25">
                      Pop. {result.employment.population.toLocaleString()}
                    </div>
                  )}
                </div>

                <div className="mt-3 pt-3 border-t border-white/5">
                  <p className="text-[10px] text-white/30 leading-relaxed">
                    Businesses hiring in this area may qualify for the Work Opportunity Tax Credit (WOTC) and workforce development incentives.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Zone Cards */}
      <div>
        <div className="flex items-center gap-4 mb-4">
          <div className="accent-bar-light" />
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
            Programs ({result.incentiveCount} of {ZONE_KEYS.length} eligible)
          </h3>
        </div>
        <div className="space-y-1">
          {sortedKeys.map((key) => (
            <ZoneResultCard
              key={key}
              zoneKey={key}
              inZone={!!result.zones[key]}
              program={programMap.get(key)}
            />
          ))}
        </div>
      </div>

      {/* Export Actions */}
      {result.incentiveCount > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="accent-bar-light" />
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
              Export Report
            </h3>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleEmail}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <Mail className="w-4 h-4" />
              Email
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-[#2563EB] hover:bg-[#1d4ed8] text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <FileText className="w-4 h-4" />
              PDF Report
            </button>
          </div>
        </div>
      )}

      {/* Next Steps */}
      {result.incentiveCount > 0 && (
        <div className="border border-white/10 p-6 rounded-xl bg-white/[0.03]">
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/60 mb-4">
            Next Steps
          </h3>
          <ol className="text-sm text-white/40 space-y-2 list-decimal list-inside">
            <li>Click each eligible program above for requirements</li>
            <li>Gather required documents for programs you want</li>
            <li>Download the PDF report for a full breakdown</li>
            <li>Visit the Programs page for full application guides</li>
          </ol>
        </div>
      )}
    </div>
  );
}
