"use client";

import { StackingScore } from "./StackingScore";
import { ZoneResultCard } from "./ZoneResultCard";
import { ZONE_KEYS } from "@/lib/constants";
import type { LookupResult, Program } from "@/lib/types";
import { Building2, MapPin, Copy, Mail, Download, Check } from "lucide-react";
import { useState, useCallback } from "react";

interface IncentiveReportProps {
  result: LookupResult;
  programs: Program[];
}

export function IncentiveReport({ result, programs }: IncentiveReportProps) {
  const [copied, setCopied] = useState(false);
  const programMap = new Map(programs.map((p) => [p.zoneKey, p]));

  const buildReportText = useCallback(() => {
    const name = result.business?.name || "Address Lookup";
    const address = result.business
      ? `${result.business.address}, Chicago, IL ${result.business.zip}`
      : result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`;

    const eligible = ZONE_KEYS
      .filter((k) => result.zones[k])
      .map((k) => programMap.get(k)?.name || k)
      .join("\n  - ");

    return `Chicago Incentive Report
========================
Business: ${name}
Address: ${address}
Incentive Score: ${result.incentiveCount} of ${ZONE_KEYS.length} zones

Eligible Programs:
  - ${eligible || "None found"}

Generated by Chicago Incentive Explorer`;
  }, [result, programMap]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(buildReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(
      `Incentive Report — ${result.business?.name || "Chicago Business"}`
    );
    const body = encodeURIComponent(buildReportText());
    window.open(`mailto:?subject=${subject}&body=${body}`);
  };

  const handleDownload = () => {
    const blob = new Blob([buildReportText()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `incentive-report-${result.business?.name?.replace(/\s+/g, "-").toLowerCase() || "chicago"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const sortedKeys = [...ZONE_KEYS].sort((a, b) => {
    const aIn = result.zones[a] ? 1 : 0;
    const bIn = result.zones[b] ? 1 : 0;
    if (aIn !== bIn) return bIn - aIn;
    return a.localeCompare(b);
  });

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="text-center space-y-3 pb-8 border-b border-white/10">
        {result.matched && result.business ? (
          <>
            <div className="flex items-center justify-center gap-2">
              <Building2 className="w-4 h-4 text-green-400" />
              <span className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-green-400">
                Matched Business
              </span>
            </div>
            <h2 className="font-editorial text-2xl text-white">{result.business.name}</h2>
            <p className="text-sm text-white/40 flex items-center justify-center gap-1">
              <MapPin className="w-3 h-3" />
              {result.business.address}, Chicago, IL {result.business.zip}
            </p>
            {result.business.category && (
              <span className="font-mono-bureau text-[9px] tracking-[0.2em] uppercase text-white/25">
                {result.business.category}
              </span>
            )}
          </>
        ) : (
          <p className="text-sm text-white/40 flex items-center justify-center gap-1">
            <MapPin className="w-3 h-3" />
            {result.address || `${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`}
          </p>
        )}
      </div>

      {/* Stacking Score */}
      <StackingScore score={result.incentiveCount} />

      {/* Zone Cards */}
      <div>
        <div className="flex items-center gap-4 mb-4">
          <div className="accent-bar-light" />
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
            Programs ({result.incentiveCount} of {ZONE_KEYS.length} eligible)
          </h3>
        </div>
        <div className="space-y-1">
          {sortedKeys.map((key) => (
            <ZoneResultCard
              key={key}
              zoneKey={key}
              inZone={!!result.zones[key]}
              program={programMap.get(key)}
            />
          ))}
        </div>
      </div>

      {/* Export Actions */}
      {result.incentiveCount > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-4">
            <div className="accent-bar-light" />
            <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/40">
              Export Report
            </h3>
          </div>
          <div className="flex gap-3">
            <button
              onClick={handleCopy}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleEmail}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-white/10 hover:bg-white/20 text-white/70 hover:text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <Mail className="w-4 h-4" />
              Email
            </button>
            <button
              onClick={handleDownload}
              className="flex-1 flex items-center justify-center gap-2.5 py-3.5 rounded-full bg-[#2563EB] hover:bg-[#1d4ed8] text-white transition-all font-mono-bureau text-[11px] tracking-wide"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>
      )}

      {/* Next Steps */}
      {result.incentiveCount > 0 && (
        <div className="border border-white/10 p-6 rounded-xl bg-white/[0.03]">
          <h3 className="font-mono-bureau text-[10px] tracking-[0.2em] uppercase text-white/60 mb-4">
            Next Steps
          </h3>
          <ol className="text-sm text-white/40 space-y-2 list-decimal list-inside">
            <li>Click each eligible program above for requirements</li>
            <li>Gather required documents for programs you want</li>
            <li>Visit the Programs page for full application guides</li>
          </ol>
        </div>
      )}
    </div>
  );
}
