/**
 * Committed CTA + Metra station coordinates, read server-side.
 *
 * SERVER ONLY — this module touches `node:fs`. Never value-import it from a
 * client component (same rule as lib/vacancy-index.ts). The pure consumers live
 * in lib/site-shortlist.ts, which takes stations as plain data.
 *
 * Static-first by repo doctrine: the shortlist's rail screen is a per-candidate
 * distance computation over ~355 points, so it must not become 355 network
 * calls. The file is regenerated by `scripts/export-rail-stations.ts`.
 */

import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import type { ShortlistStation } from "./site-shortlist";

export interface RailStationsFile {
  generatedAt: string;
  sources: string[];
  stations: (ShortlistStation & { ada: boolean | null })[];
}

const RAIL_STATIONS_PATH = path.join(process.cwd(), "public/data/rail-stations.json");

// Module-level cache, read once per process (mirrors loadVacancyIndex).
let cache: RailStationsFile | null | undefined = undefined;

/** The committed station file, or `null` when it is absent or unparseable. */
export function loadRailStations(): RailStationsFile | null {
  if (cache !== undefined) return cache;

  try {
    if (!existsSync(RAIL_STATIONS_PATH)) {
      cache = null;
      return cache;
    }
    const parsed = JSON.parse(readFileSync(RAIL_STATIONS_PATH, "utf8")) as unknown;
    cache =
      parsed &&
      typeof parsed === "object" &&
      Array.isArray((parsed as RailStationsFile).stations)
        ? (parsed as RailStationsFile)
        : null;
  } catch {
    cache = null;
  }

  return cache;
}

/** Just the coordinates the shortlist screens against; `[]` when unavailable,
 *  which degrades to "no rail screen, no rail score" rather than throwing. */
export function railStations(): ShortlistStation[] {
  const file = loadRailStations();
  if (!file) return [];
  return file.stations.filter(
    (station) =>
      typeof station.lat === "number" &&
      typeof station.lon === "number" &&
      Number.isFinite(station.lat) &&
      Number.isFinite(station.lon),
  );
}
