import { execFileSync } from "node:child_process";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Sol gate finding 2 (BLOCKER, round 2) — "IDs must survive a middle insert
 * of a DISTINCT row with zero downstream renumbering... The baseline must be
 * a FROZEN COMMITTED fixture file (generated once, checked in, never
 * regenerated by the test)."
 *
 * scripts/foundation/test_identity_stability.py exercises the PURE identity
 * functions (assign_occurrence_indices, node_fingerprint, stable_id,
 * select_amended_resolved_filings) against
 * scripts/foundation/fixtures/identity_baseline.json — a FROZEN, COMMITTED
 * baseline (generated once by a throwaway script, never touched by this test
 * or by build_grant_identity.py's normal run) — asserting BYTE-IDENTICAL
 * stable_ids for every pre-existing row after a middle-insert or an append of
 * a DISTINCT row, plus the documented identical-duplicate-occurrence-suffix
 * boundary. No network. It DOES transitively import phase2_pipeline.py,
 * though, which creates its XML/funder cache directories at MODULE LOAD time
 * under `PHASE2_STATE` (a hard-coded macOS scratchpad path when unset) —
 * harmless on the machine that path was authored on, but a
 * `PermissionError` on any other machine, including a Linux CI runner where
 * `/private` does not exist. PHASE2_STATE is set here to a portable per-test
 * tmp dir so this test runs identically everywhere, never touching the real
 * (macOS-only) default.
 */
describe("foundation identity stability (Sol gate finding 2)", () => {
  it("MIDDLE-INSERT/APPEND survive with zero renumbering vs. the frozen fixture; UNIQUENESS/SUPERSESSION/duplicate-boundary all pass", () => {
    const portableState = mkdtempSync(join(tmpdir(), "phase2-state-"));
    expect(() => {
      execFileSync("python3", ["scripts/foundation/test_identity_stability.py"], {
        cwd: process.cwd(),
        stdio: "pipe",
        env: { ...process.env, PHASE2_STATE: portableState },
      });
    }).not.toThrow();
  }, 30_000);
});
