#!/usr/bin/env npx tsx
/**
 * Database migration for durable, immutable Permit Exhibit snapshots.
 *
 * Snapshots belong to the professional-access gate, not to a user account.
 * The public, display, and request IDs are random identifiers generated by the
 * application. Duplicated columns make the integrity envelope independently
 * queryable and are checked against the full JSONB document on every insert.
 *
 * Usage:
 *   DATABASE_URL="postgresql://..." npx tsx scripts/migrate-permit-exhibit-snapshots.ts
 */

import { neon } from "@neondatabase/serverless";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL environment variable is required");
  process.exit(1);
}

const sql = neon(DATABASE_URL);

async function main() {
  console.log("Running Permit Exhibit snapshot migration...\n");

  console.log("1. Creating append-only snapshot storage...");
  await sql`
    CREATE TABLE IF NOT EXISTS permit_exhibit_snapshots (
      public_id TEXT PRIMARY KEY
        CHECK (public_id ~ '^ps_[A-Za-z0-9_-]{24}$'),
      display_id TEXT NOT NULL UNIQUE
        CHECK (display_id ~ '^PX-[0-9]{14}-[0-9]{8}-[A-Z0-9]{4,8}$'),
      request_id UUID NOT NULL UNIQUE,
      pin TEXT NOT NULL
        CHECK (pin ~ '^[0-9]{14}$'),
      radius_ft INTEGER NOT NULL
        CHECK (radius_ft IN (250, 500, 1000)),
      snapshot_schema_version INTEGER NOT NULL
        CHECK (snapshot_schema_version > 0),
      saved_at TIMESTAMPTZ NOT NULL,
      content_hash TEXT NOT NULL
        CHECK (content_hash ~ '^[0-9a-f]{64}$'),
      app_revision TEXT NOT NULL
        CHECK (length(app_revision) BETWEEN 1 AND 120),
      snapshot_json JSONB NOT NULL
        CHECK (jsonb_typeof(snapshot_json) = 'object'),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

      CONSTRAINT permit_exhibit_snapshots_public_id_matches_json
        CHECK ((snapshot_json ->> 'publicId') IS NOT DISTINCT FROM public_id),
      CONSTRAINT permit_exhibit_snapshots_display_id_matches_json
        CHECK ((snapshot_json ->> 'displayId') IS NOT DISTINCT FROM display_id),
      CONSTRAINT permit_exhibit_snapshots_schema_version_matches_json
        CHECK (
          (snapshot_json ->> 'schemaVersion')::integer
            IS NOT DISTINCT FROM snapshot_schema_version
        ),
      CONSTRAINT permit_exhibit_snapshots_saved_at_matches_json
        CHECK (
          (snapshot_json ->> 'savedAt')::timestamptz
            IS NOT DISTINCT FROM saved_at
        ),
      CONSTRAINT permit_exhibit_snapshots_app_revision_matches_json
        CHECK ((snapshot_json ->> 'appRevision') IS NOT DISTINCT FROM app_revision),
      CONSTRAINT permit_exhibit_snapshots_pin_matches_json
        CHECK (
          (snapshot_json #>> '{exhibit,meta,subjectParcel,pin}')
            IS NOT DISTINCT FROM pin
        ),
      CONSTRAINT permit_exhibit_snapshots_radius_matches_json
        CHECK (
          (snapshot_json #>> '{exhibit,meta,queryParams,radiusFt}')::integer
            IS NOT DISTINCT FROM radius_ft
        )
    )
  `;

  await sql`
    CREATE OR REPLACE FUNCTION reject_permit_exhibit_snapshot_mutation()
    RETURNS TRIGGER AS $$
    BEGIN
      RAISE EXCEPTION 'Permit Exhibit snapshots are immutable and cannot be updated or deleted';
      RETURN OLD;
    END;
    $$ LANGUAGE plpgsql
  `;

  await sql`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'trg_permit_exhibit_snapshots_reject_mutation'
          AND tgrelid = 'permit_exhibit_snapshots'::regclass
      ) THEN
        CREATE TRIGGER trg_permit_exhibit_snapshots_reject_mutation
        BEFORE UPDATE OR DELETE ON permit_exhibit_snapshots
        FOR EACH ROW
        EXECUTE FUNCTION reject_permit_exhibit_snapshot_mutation();
      END IF;
    END
    $$
  `;

  console.log("2. Creating snapshot indexes...");
  await sql`
    CREATE INDEX IF NOT EXISTS idx_permit_exhibit_snapshots_pin_saved_at
    ON permit_exhibit_snapshots (pin, saved_at DESC)
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_permit_exhibit_snapshots_created_at
    ON permit_exhibit_snapshots (created_at DESC)
  `;

  console.log("3. Creating rate-limit attempt storage...");
  await sql`
    CREATE TABLE IF NOT EXISTS permit_exhibit_snapshot_attempts (
      id BIGSERIAL PRIMARY KEY,
      client_hash TEXT NOT NULL
        CHECK (client_hash ~ '^[0-9a-f]{64}$'),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_permit_exhibit_snapshot_attempts_client_created_at
    ON permit_exhibit_snapshot_attempts (client_hash, created_at DESC)
  `;
  await sql`
    CREATE INDEX IF NOT EXISTS idx_permit_exhibit_snapshot_attempts_created_at
    ON permit_exhibit_snapshot_attempts (created_at DESC)
  `;

  await sql`
    CREATE OR REPLACE FUNCTION reserve_permit_exhibit_snapshot_attempt(
      requested_client_hash TEXT,
      hourly_limit INTEGER
    )
    RETURNS BOOLEAN AS $$
    DECLARE
      recent_count INTEGER;
    BEGIN
      IF requested_client_hash !~ '^[0-9a-f]{64}$' OR hourly_limit < 1 THEN
        RAISE EXCEPTION 'Invalid Permit Exhibit snapshot rate-limit request';
      END IF;

      -- VOLATILE PL/pgSQL statements take fresh READ COMMITTED snapshots. The
      -- transaction-scoped per-client lock therefore serializes the count and
      -- insert even when many serverless requests arrive together.
      PERFORM pg_advisory_xact_lock(hashtextextended(requested_client_hash, 0));
      SELECT COUNT(*)::integer
        INTO recent_count
        FROM permit_exhibit_snapshot_attempts
       WHERE client_hash = requested_client_hash
         AND created_at >= NOW() - INTERVAL '1 hour';

      IF recent_count >= hourly_limit THEN
        RETURN FALSE;
      END IF;

      INSERT INTO permit_exhibit_snapshot_attempts (client_hash)
      VALUES (requested_client_hash);
      RETURN TRUE;
    END;
    $$ LANGUAGE plpgsql VOLATILE
  `;

  console.log("\nPermit Exhibit snapshot storage is ready.");
}

main().catch((error) => {
  console.error("Permit Exhibit snapshot migration failed:", error);
  process.exit(1);
});
